#!/bin/bash
# Permission UI hook for Claude Code
# Generated by ui-mcp hooks install
# Spec: prompt-ui.md
set -e

# Read hook input from stdin
input=$(cat)

# Extract details from hook data
tool_name=$(echo "$input" | jq -r '.tool_name // "unknown tool"')
tool_input=$(echo "$input" | jq -c '.tool_input // {}')
message="Claude wants to use: $tool_name"

# Read MCP port
MCP_PORT=$(cat .ui-mcp/mcp-port 2>/dev/null || echo "")
if [ -z "$MCP_PORT" ]; then
  # UI MCP not running, fall back to terminal
  exit 0
fi

# Build prompt request
request=$(jq -n \
  --arg msg "$message" \
  '{
    "message": $msg,
    "options": [
      {"label": "Allow once", "value": "allow"},
      {"label": "Always allow", "value": "allow_session"},
      {"label": "Deny", "value": "deny"}
    ],
    "timeout": 60
  }')

# Call prompt API
response=$(curl -s -X POST "http://127.0.0.1:$MCP_PORT/api/prompt" \
  -H "Content-Type: application/json" \
  -d "$request" 2>/dev/null || echo '{"error": "failed"}')

# Check for error
if echo "$response" | jq -e '.error' >/dev/null 2>&1; then
  # API call failed, fall back to terminal
  exit 0
fi

# Parse response
value=$(echo "$response" | jq -r '.value')
label=$(echo "$response" | jq -r '.label')

# Log decision for pattern analysis
log_entry=$(jq -n \
  --arg tool "$tool_name" \
  --argjson input "$tool_input" \
  --arg choice "$value" \
  --arg ts "$(date -Iseconds)" \
  '{tool: $tool, input: $input, choice: $choice, timestamp: $ts}')
echo "$log_entry" >> .ui-mcp/permissions.log

# Return hook decision
case "$value" in
  "allow"|"allow_session")
    echo '{"decision": "allow"}'
    ;;
  "deny")
    echo '{"decision": "deny", "message": "User denied permission"}'
    ;;
  *)
    # Timeout or error - let terminal prompt handle it
    exit 0
    ;;
esac
